name: Backend Auto-Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Backend to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/memology-backend
            git fetch origin main
            git reset --hard origin/main
            git clean -fd
            docker compose down
            docker compose build
            docker compose up -d
            echo '--- Logs for the Latest Container ---'
            docker logs $(docker ps -lq)

      - name: Verify Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/memology-backend
            git status
            docker ps
            echo '--- Health Check ---'
            sleep 5
            curl -f http://localhost:8080/swagger/doc.json || echo 'Health check failed'
